### ISSUE TITLE
Expunged and removed search options

### ISSUE THREAD

**Issue by poontology** [UBTL/pandabrowser#7]
Expunged and removed search options don't actually work right now because in app/action/search.js they default to 1 (include) and searchbox only sets them as URL-params if the checkboxes are checked, in other words they are always true.

This could be fixed either in searchbox so that it always sends the checkbox value as URL-param despite the value, or by changing the default in search.js to 0 (exclude). I'm in favor of excluding expunge/removed from search by default.

**Comment by UBTL** [comment]
oh yeah I remember  hardcoded the setting to true for the public release because the idea of this project after all was to be a solution for people to be able to browse the Panda database and look up mainly stuff that has been expunged and the like first and foremost since my related UBUCA projects are related to archival of that stuff too and then ideally a second thing that it could be used would be stuff like get metadata off it for those wishing to other projects like say Lanraragi and get their metadata off from here rather than go and so from panda and get their IPs banned.
Excluding Expunged/Removed galleries from the search imho completely invalidates the original main usage for this project that is basically being a tool for get data and the like from removed content off Panda

**Comment by poontology** [comment]
They should definitely still be searchable yes I meant just changing the defaults so users wanting them would have to check the box in advanced options, but I don't have a strong preference having them on initially is ok by me (after all I can save my default preferences to localStorage :slightly_smiling_face:) we'll just have to fix the searchbox so it sends unchecked options.
